MOV R0, #0CH
MOV R1, #0AH
MOV R2, #41H
MOV R3, #0A5H
CLR C
LOOP:	MOV A, R3
		SUBB A, R1
		JC HLT
		JNZ LOOP1
		CLR C
		MOV A, R2
		SUBB A, R0
		JC HLT
LOOP1:	CLR C
		MOV A, R2
		SUBB A, R0
		MOV R2, A
		MOV A, R3
		SUBB A, R1
		MOV R3, A
		INC DPTR
		SJMP LOOP
HLT:	SJMP HLT
END
// A541/0A0C = 10H REM(481H)
//QUOTIENT STORED IN DPTR REG,
//REMAINDER STORED IN R3,R2 REG.