;P1.0-P1.7 -> DB0-DB7
;P0.2->RS
;P0.1->R/W
;P0.0->E
;SENDING INFO TO LCD USING MOVC COMMAND
;SCROLLING DATA ON THE SCREEN 
ORG 0H
MOV DPTR,#MYCOM
;LOOP C1 UNTIL MYCOM TABLE(DATA) VALUES REACH END
C1:	CLR A
	MOVC A,@A+DPTR
	ACALL CMDWRT
	JZ SEND_DATA;IF A=0,MOVE TO SEND_DATA LOOP
	INC DPTR
	SJMP C1	
SEND_DATA:	MOV R0,#90H
			MOV B,#0FFH
			LOOPOF8:	DEC R0
						INC B
						MOV DPTR,#MYDATA
						D1:	MOV A,R0	;SETTING THE CURSOR TO THE RIGHT OF SCREEN
						ACALL CMDWRT
						INC R0
						MOV A,B
						MOVC A,@A+DPTR
						ACALL DATAWRT
						JZ HLT
						INC DPTR
						CJNE R0,#90H,D1
						ACALL DELAY
						SJMP LOOPOF8 

HLT: SJMP HLT	;STAY HERE

CMDWRT:	ACALL READY
		MOV P1,A
		CLR P0.2	;RS=0
		CLR P0.1	;R/W=0
		;CREATE A HIGH TO LOW TRIGGER
		SETB P0.0	;ENABLE HIGH
		CLR P0.0	;ENABLE LOW
		RET
DATAWRT:ACALL READY
		MOV P1,A
		SETB P0.2	;RS=0
		CLR P0.1	;R/W=0--WRITE
		;CREATE A HIGH TO LOW TRIGGER
		SETB P0.0	;ENABLE HIGH
		CLR P0.0	;ENABLE LOW
		RET
DELAY:	MOV R3,#0FFH
		MOV R4,#0FFH
		MOV R5,#55H
		HERE:	DJNZ R5,HERE
		HERE1:	DJNZ R4,HERE1
		HERE2:	DJNZ R3,HERE2
		RET
READY:	SETB P1.7	;SET P1.7 AS INPUT PORT TO READ BUSY FLAG FROM DB7 PIN OF LCD
		SETB P0.2	;R/W=1--READ
		CLR P0.2	;R/S=0--COMMAND
		;READ COMMAND REG AND CHECK BUSY FLAG
		BACK:	;CREATE A LOW TO HIGH TRIGGER, WHY?? TO READ FROM LCD??
				CLR P0.0	;ENABLE LOW
				SETB P0.0	;ENABLE HIGH
				JB P1.7,BACK
		RET
ORG 300H
MYCOM:	DB 38H,0EH,01H,0	;COMMAND AND NULL
MYDATA:	DB ' ',' ',' ',' ',' ',' ',' ',' ','K','E','V,','A','L',' ','D','.',' ','R','A','N','A',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',0			;DATA AND NULL
END

