START:	MOV R0,#08H
		MOV A,#01H
		JB P0.0,LOOPL
LOOPR:	MOV A,#80H
		LOOP:	MOV B,A
				RR A
				ADD A,B
				MOV P1,A
				ACALL DELAY
				CLR C
				SUBB A,B
				MOV P1,A
				ACALL DELAY
				MOV P1,#00H
				;RR A	; IF WISHING TO MOVE IN TWO STEPS
				;DEC R0	
				DJNZ R0,LOOP
		SJMP START
				
LOOPL:	MOV B,A
		RL A
		ADD A,B
		MOV P1,A
		ACALL DELAY
		CLR C
		SUBB A,B
		MOV P1,A
		ACALL DELAY
		MOV P1,#00H
		;RL A	; IF WISHING TO MOVE IN TWO STEPS
		;DEC R0	
		DJNZ R0,LOOPL
		SJMP START
DELAY:	MOV R1,#08H
		L3:	MOV R2,#0FFH
		L2:	MOV R3,#0FFH
		L1:	DJNZ R3,L1
		DJNZ R2,L2
		DJNZ R3,L3
		RET
END
		
