START:	MOV A,#01H
		SETB P0.0	;MAKE P0.0 AS INPUT
MOV R0,#04H
JB P0.0,LOOP2
ROTRL:	MOV R1,#08H	
;ASSIGN THE NUMBER OF LEDS AVAILABLE
;IGNORE,ILLOGICAL COMMENT, REGISTER SIZE CANT EXCEED 8(8 BITS)
				MOV P1,A	;P1 IS CONNECTED TO LED
				ACALL DELAY
				RL A
				DJNZ R1,ROTRL
				MOV P1,#00H
				ROTLR:	MOV R1,#08H
						MOV P1,A
						ACALL DELAY
						RR A
						DJNZ R1,ROTLR
		DJNZ R0,ROTRL
		SJMP LAST
LOOP2:	MOV R1,4	; R1 IS NUMBER OF LED STEPS FOR ONE CYCLE
		MOV A,#01H
		MOV B,A
		RR A
		MOV R3,A
		CYCLE:	MOV A,R3
				ADD A,B
				MOV P1,A
				ACALL DELAY
				MOV A,R3
				RR A
				MOV R3,A
				MOV A,B
				RL A
				MOV B,A 
				DJNZ R1,CYCLE
		DJNZ R0,LOOP2
		SJMP LAST
LAST:	MOV P1,#0FFH
		ACALL DELAY
		SJMP START
DELAY:	MOV R1,#08H
		L3:	MOV R2,#0FFH
		L2:	MOV R3,#0FFH
		L1:	DJNZ R3,L1
		DJNZ R2,L2
		DJNZ R3,L3
		RET
END